export const enum Vendor {
  fontawesome = 'fontawesome',
  heroicons = 'heroicons',
  feathericons = 'feathericons',
  linearicons = 'linearicons',
  dripicons = 'dripicons',
  lineawesome = 'lineawesome',
  ikonate = 'ikonate',
  remixicon = 'remixicon',
  twemoji = 'twemoji',
  emojitwo = 'emojitwo',
  notoemoji = 'notoemoji',
  openmoji = 'openmoji',
  svgporn = 'svgporn',
  healthicons = 'healthicons',
}
export const VENDORS = [
  Vendor.fontawesome,
  Vendor.heroicons,
  Vendor.feathericons,
  Vendor.linearicons,
  Vendor.dripicons,
  Vendor.lineawesome,
  Vendor.ikonate,
  Vendor.remixicon,
  Vendor.twemoji,
  Vendor.emojitwo,
  Vendor.notoemoji,
  Vendor.openmoji,
  Vendor.svgporn,
  Vendor.healthicons,
];
