export const VENDORS = [
  Vendor.fontawesome,
  Vendor.heroicons,
  Vendor.feathericons,
  Vendor.linearicons,
  Vendor.dripicons,
  Vendor.lineawesome,
  Vendor.ikonate,
  Vendor.remixicon,
  Vendor.twemoji,
  Vendor.emojitwo,
  Vendor.notoemoji,
  Vendor.openmoji,
  Vendor.svgporn,
];
