version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          key: composer-{{ checksum "composer.json" }}
          paths:
           - vendor
      - run: composer install -n --prefer-dist
      - run: make php-qa
      - run: make php-tests
      - save_cache:
          key: composer-{{ checksum "composer.json" }}
          paths:
            - vendor
